[build]
  command = "npm run build"      # Your build command
  publish = "dist"               # "dist" for Vite, "build" for CRA
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[cache]
  paths = [
    "node_modules/.cache"        # For tools like Vite
  ]
